FROM alpine:3
RUN apk add --no-cache nfs-ganesha nfs-ganesha-vfs
RUN mkdir -p /var/lib/nfs/ganesha /var/run/ganesha
EXPOSE 2049/tcp
ENTRYPOINT ["/usr/bin/ganesha.nfsd", "-F", "-L", "STDOUT", "-f", "/etc/ganesha/ganesha.conf"]
